### ISSUE TITLE
how to open with sublime?

### ISSUE THREAD

**Issue by jackyon** [royriojas/eslint-friendly-formatter#16]
hi,

after looking through the doc, i still don't know how to use with sublime.

in my terminal, it's only shows the error and file path, the path can not be able to clicked:
![cd80cbce-63f0-400a-9fd2-b95393437060](https://cloud.githubusercontent.com/assets/1758938/13781484/79d15f3e-eafe-11e5-875d-0d2e8149b951.png)

plz advise how to deal with this.
thx.

**Comment by royriojas** [comment]
Hi @jackyon 

A couple of questions:

- If you're using mac are you using [iterm2](https://www.iterm2.com/downloads.html)? 
- If you're using Linux have you configure your terminal to follow local links as suggested [here](http://unix.stackexchange.com/questions/63417/is-there-a-terminal-app-that-allows-filenames-to-be-clickable)

**Comment by jackyon** [comment]
hi @royriojas 

yes, I am using mac, I have tried both iterm2 and item from the OSX  system, both are not able to click the file path.

**Comment by denlinsley** [comment]
Try using Command + click. That works for me.

**Comment by jackyon** [comment]
@denlinsley  not working for me.. that's weird, anyway, thx your tip.

**Comment by royriojas** [comment]
In iterm2 there is an option under `preferences/profiles` that controls the behavior of `command + click`
![screen shot 2016-04-08 at 4 42 19 pm](https://cloud.githubusercontent.com/assets/131290/14398332/eaceb152-fda8-11e5-9d76-156b6390c529.png)

Can you check you have the same config?

**Comment by jackyon** [comment]
thank you, the config was a little bit difference, I don't know why.

anyway, problem solved! thank you guys!

**Comment by royriojas** [comment]
you're welcome!
