### ISSUE TITLE
on windows 7 single quotes not needed for npm script

### ISSUE THREAD

**Issue by t0lkman** [royriojas/eslint-friendly-formatter#17]
in my case, this doesn't work (complains that cannot find module)
"eslint": "eslint --format 'node_modules/eslint-friendly-formatter' file1 file2 dir1/ dir2/",

but this works

"eslint": "eslint --format node_modules/eslint-friendly-formatter file1 file2 dir1/ dir2/",

**Comment by royriojas** [comment]
Oh, thanks, 

Will update the README with this info. Thank you very much.
