### ISSUE TITLE
Screenshot in Readme is hard to read

### ISSUE THREAD

**Issue by IanVS** [royriojas/eslint-friendly-formatter#19]
I think there is a transparency in the screenshot, which makes it very difficult to see.

**Comment by royriojas** [comment]
hi @IanVS,

It is true. Will fix it to make it more friendly :)

**Comment by paulirish** [comment]
yes please. :)

**Comment by royriojas** [comment]
Hope the last one is better :)

**Comment by IanVS** [comment]
Much better.  :)  Thanks.
