### ISSUE TITLE
Unable to get working with Webstorm?

### ISSUE THREAD

**Issue by mikeerickson** [royriojas/eslint-friendly-formatter#24]
I have tried to get this external tool to work with WebStorm but having issues?   I have followed all the steps outlined in readme, but it doesnt seem to "kick in"

**Comment by royriojas** [comment]
hi @mikeerickson,

can you provide the version of webstorm you are using?

**Comment by penguin999** [comment]
Hi @royriojas,

I am using `WebStorm 2017.1.1`. I see errors and "gray links" reported nicely in WebStorm's terminal; however, clicking on them does not take me to the file/line/column of the error.

In any case, I am finding your module useful as noted below. Many thanks!

@mikeerickson,

As a workaround (on a Mac), I 
* double-click the "link" to select it
* `command-c` to copy it
* `shift-command-o` (or `Navigate > File...` from the main menu) to open the Navigate File dialog box
* `commad-v` to paste
* press `return/enter` to open the file with the cursor at the correct line/column
* rejoice :) 

I cannot do this with the default output; it does not provide a usable file/line/column format; and, I have not found any preference/setting within WebStorm that allows "good formatted links" like Roy's to work with a simple click.

**Comment by jensfranke** [comment]
I have the same issue with PHPStorm:

PhpStorm 2017.1
Build #PS-171.3780.104, built on March 21, 2017
JRE: 1.8.0_112-release-736-b13 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.11.6

definition in my package.json:

`"lint": "eslint --format 'node_modules/eslint-friendly-formatter' **/client/**/*.{vue,js} !node_modules/**"`

and I run it via `npm run lint`

Both links (ESLint and Source-Files are not clickable)

Thanks in advance for your help

**Comment by royriojas** [comment]
hi @jensfranke, Sadly I have not a license phpStorm anymore, so I can't really test... maybe asking in the phpStorm support forum? I will see if I can get one, but the one I might have at hand it is definitively older now :(

Not sure the colors has something to do with the issue but maybe removing the colors with `TERM=dumb` like in the following command will help

```
"lint": "TERM=dumb eslint --format 'node_modules/eslint-friendly-formatter' **/client/**/*.{vue,js} !node_modules/**",
```

**Comment by royriojas** [comment]
I just tested this in latest webstorm and it works, right now we don't need to add spaces before the pattern to make it work. Just doing this worked for me:

![screen shot 2017-08-09 at 6 02 37 pm](https://user-images.githubusercontent.com/131290/29147493-fafef622-7d2c-11e7-9938-e7fbb31dbc40.png)

Closing this one. Please feel free to reopen if this is still not working for you.
