### ISSUE TITLE
Clickable Paths

### ISSUE THREAD

**Issue by stevenleija** [royriojas/eslint-friendly-formatter#25]
From inside of IntelliJ I'm able to get the formatter to work via external command perfectly.  Both the hyperlink to the rule and the file are clickable and brings up to perfection.

When running from gulp the file is still clickable from the "Run" panel but the hyperlink is broken or not clickable.  The url appears to be clickable as it's underlined until just past the specific rule.  

eg. http://eslint.org/docs/rules/no-console

"http://eslint.org/docs/rules/" is underlined and appears clickable and the "no-console" is not underlined.  But none of it is clickable like it is when I run in the external tool.

Is there something that needs to be configured in gulp to allow the links to the rules clickable?

![screen shot 2017-03-16 at 5 06 11 pm](https://cloud.githubusercontent.com/assets/124998/24020627/f3abbbd8-0a6a-11e7-857a-16df17a73698.png)

**Comment by royriojas** [comment]
Hi @stevenleija, 

It is probably the color codes that are messing with the clickable paths. Will see if that can be removed somehow and let you know.

**Comment by royriojas** [comment]
For this case it seems it is possible to pass `TERM=dumb` to remove the colors, doing that the links should be clickable again.

Please feel free to reopen if this doesn't help. Closing for now.
