### ISSUE TITLE
Publish on npm as eslint-formatter-friendly ?

### ISSUE THREAD

**Issue by InvictusMB** [royriojas/eslint-friendly-formatter#34]
Eslint recently became smarter in resolving plugin names so if this package is published with their naming convention (e.g. prefixed with `eslint-formatter-`) it would make the CLI usage less verbose.

Before:
`"eslint": "eslint --format 'node_modules/eslint-friendly-formatter' file1 file2 dir1/ dir2/"`

After:
`"eslint": "eslint --format friendly file1 file2 dir1/ dir2/"`

It is especially helpful in lerna managed repositories as the script there is even more ugly for nested packages:
`"eslint": "eslint --format '../../node_modules/eslint-friendly-formatter' file1 file2 dir1/ dir2/"`

**Comment by royriojas** [comment]
@InvictusMB interesting, yeah sure. It makes a lot of sense. Will publish the package if name is available.

**Comment by JounQin** [comment]
Why not change the name of this repository to `eslint-formatter-friendly` but create a new one? If you change the name, the former links will be redirected to new one correctly, what means there is no need to create another same repository.

**Comment by royriojas** [comment]
Yeah I tried it, but run into some issues. Not sure why as you said links would have been redirected but didn't work at first try. 

Then I renamed again and created a new one.

Will see if possible to unify both repos.
