### ISSUE TITLE
Google search link seems outdated

### ISSUE THREAD

**Issue by Xerillio** [royriojas/eslint-friendly-formatter#45]
Before going into details, is this project still active? It seems there hasn't been much activity for a few years.

## The bug report

The formatter produces links for non-standard/3rd party ESLint rules by pointing to Google Search with the following prefix in the URL: `https://google.com/#q=`. It seems this is an outdated format for Google Search links and it should instead be: `https://google.com/search?q=`.

If it's of any interest, I'll happily create a pull request for this fix as well as for a few other additions/improvements you can find in my fork here: [Xerillio/eslint-friendly-formatter](https://github.com/Xerillio/eslint-friendly-formatter)

**Comment by royriojas** [comment]
sure that would be awesome!

**Comment by Xerillio** [comment]
@royriojas I've added a PR now. I'll create another issue with some suggested additions you can consider if you want to include in this project.

**Comment by royriojas** [comment]
Thanks @Xerillio will review it
