### ISSUE TITLE
Use rule metadata to get documentation link

### ISSUE THREAD

**Issue by IanVS** [royriojas/eslint-friendly-formatter#52]
Instead of falling back to google immediately, the formatter could look at `meta.docs.url`: https://eslint.org/docs/latest/extend/custom-rules

**Comment by ajitzero** [comment]
@IanVS This repo has been replaced by https://github.com/royriojas/eslint-formatter-friendly

**Comment by IanVS** [comment]
Thanks, it seems this repo should be archived, @royriojas?
