### ISSUE TITLE
Reason for absolute path?

### ISSUE THREAD

**Issue by mathieumg** [royriojas/eslint-friendly-formatter#7]
Is there any reason the path is made absolute in https://github.com/royriojas/eslint-friendly-formatter/blob/a8c3c710008a9aa0993836f8b4a4419c0ec39de9/index.js#L51? I would like to keep the path as outputted initially by ESLint and making it absolute also breaks the Guake quick open feature.

Thanks!

**Comment by royriojas** [comment]
iterm2 does not play well with relative ones. Maybe an environment variable to modify this? I'm not aware if the formatters can receive parameters from eslint. Can they?

If not I guess the env variable solution might help.  

pull requests welcome.

**Comment by royriojas** [comment]
Fixed and released [v.1.1.0](https://github.com/royriojas/eslint-friendly-formatter/blob/master/changelog.md#v110)
